name: Test

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Set Execution Policy
        if: runner.os == 'Windows'
        shell: pwsh
        run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Activate virtual environment
        shell: pwsh
        run: . ./.venv/Scripts/activate

      - name: Lint with flake8
        run: flake8 app/

      - name: Test with pytest
        timeout-minutes: 5
        run: pytest tests/ --cov=app --cov-report term-missing
