name: Test

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: windows-latest  # Use windows-latest for PowerShell

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Set Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Activate virtual environment
        shell: pwsh
        run: . ./.venv/Scripts/activate

      - name: Lint with flake8
        run: flake8 app/

      - name: Test with pytest
        timeout-minutes: 5
        run: pytest tests/ --cov=app --cov-report term-missing
